version: 2.1

jobs:
  build:
    docker:
      - image: cimg/openjdk:11.0.11-node
    working_directory: ~/project

    steps:
      - checkout

      - run:
          name: Build with Maven
          command: mvn clean install

      - run:
          name: Run Tests
          command: mvn test

workflows:
  build-and-deploy:
    jobs:
      - build